const items=[
    {
        id:'001',
        image:'images/img1.webp',
        company:'Roadster',
        item_name:'Pure Cotton Casual shirt',
        original_price:1899,
        current_price:702,
        discount_percentage:63,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.2,
            count:431,
        },
    },
    {    id:'002',
        image:'images/img2.webp',
        company:'V-Mart',
        item_name:'Women cardigan',
        original_price:799,
        current_price:799,
        discount_percentage:0,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:0,
            count:0,
        },
    },
    {    id:'004',
        image:'images/img4.webp',
        company:'Vella Bita organic ',
        item_name:'Luxury Unisex 4pc Perfume Gift',
        original_price:849,
        current_price:577,
        discount_percentage:32,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.4,
            count:98,
        },
    },
    {    id:'003',
        image:'images/img3.webp',
        company:'Wynona',
        item_name:'Jewellery Set',
        original_price:1499,
        current_price:1049,
        discount_percentage:30,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.4,
            count:90,
        },
    },
    {    id:'005',
        image:'images/img5.webp',
        company:'Noh.Voh -  SASSAFRAS kids',
        item_name:'Girls Straight Fit Jeans',
        original_price:2199,
        current_price:791,
        discount_percentage:64,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.3,
            count:410,
        },
    },
    {    id:'006',
        image:'images/img6.webp',
        company:'Hilary Rhoda',
        item_name:'Concealer -12g-3',
        original_price:269,
        current_price:269,
        discount_percentage:0,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.2,
            count:1200,
        },
    },
    {    id:'007',
        image:'images/img7.webp',
        company:'WEAVING HOMES',
        item_name:'10pcs Ceramic Cups ',
        original_price:3449,
        current_price:2966,
        discount_percentage:14,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.6,
            count:1600,
        },
    },
    {     id:'008',
        image:'images/img8.webp',
        company:'Roadster',
        item_name:'Women Pointed Toe Block Heel',
        original_price:2499,
        current_price:999,
        discount_percentage:60,
        return:14,
        dilivery_on: '21 jan 2025',
        rating:{
            stars:4.3,
            count:1002,
        },
    },
   
];